apiVersion: v1
kind: Service
metadata:
  name: lighthouse-service
spec:
  type: NodePort
  selector:
    app: lighthouse
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
      nodePort: 31008
